platform :ios, '12.0'

target 'EpisodeTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EpisodeTracker
  pod 'Kingfisher', '5.11.0'
  pod 'MaterialComponents/Ripple', '100.0.0'
  pod 'MaterialComponents/Tabs', '100.0.0'
  pod 'MaterialComponents/Buttons', '100.0.0'
  pod 'ReachabilitySwift', '5.0.0'
  pod 'IGListKit', '4.0.0'
  pod 'SwipeCellKit', '2.7.1'

  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings['LD_RUNPATH_SEARCH_PATHS'] = [
        '$(FRAMEWORK_SEARCH_PATHS)'
      ]
    end
  end

end
