platform :ios, '12.0'

target 'EpisodeTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EpisodeTracker
  pod 'Kingfisher', '5.11.0'
  pod 'MaterialComponents/Ripple', '100.0.0'
  pod 'MaterialComponents/Tabs', '100.0.0'

end
